version: '3'

services:
  growi0084108:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 30108:3000
    links:
      - mongo0084108:mongo
      - elasticsearch0084108:elasticsearch
    depends_on:
      - mongo0084108
      - elasticsearch0084108
    environment:
      - MONGO_URI=mongodb://mongo:27017/growi
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi
      - PASSWORD_SEED=changeme
      - FILE_UPLOAD=local     # activate this line if you use local storage of server rather than AWS

    entrypoint: "dockerize
                  -wait tcp://mongo:27017
                  -wait tcp://elasticsearch:9200
                  -timeout 60s
                  /docker-entrypoint.sh"
    command: ["yarn migrate && node -r dotenv-flow/config --expose_gc dist/server/app.js"]

    restart: unless-stopped
    volumes:
      - growi_data0084108:/data
    networks:
      - aix_infra

  mongo0084108:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongo_configdb0084108:/data/configdb
      - mongo_db0084108:/data/db
    networks:
      - aix_infra

  elasticsearch0084108:
    build:
      context: ./elasticsearch
      dockerfile: ./Dockerfile
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # increase amount if you have enough memory
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true # CVE-2021-44228 mitigation for Elasticsearch <= 6.8.20/7.16.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - es_data0084108:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - aix_infra

volumes:
  growi_data0084108:
  mongo_configdb0084108:
  mongo_db0084108:
  es_data0084108:

networks:
  aix_infra:
    external: true


